spin_manifest_version = "1"
authors = ["Jason Washburn <jason.washburn@gmail.com>"]
description = ""
name = "python-gha-test"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "python-gha-test"
source = "app.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "spin py2wasm app -o app.wasm"
